# Groq (free tier available, very fast)
[[players]]
id = "RED"
type = "llm"
model = "openai/gpt-oss-120b"
api_base = "https://api.groq.com/openai/v1"
api_key_env = "GROQ_API_KEY"
reasoning_enabled = false
timeout_seconds = 300
temperature = 0.6
top_p = 0.95

# Together AI
[[players]]
id = "ORANGE"
type = "llm"
model = "moonshotai/Kimi-K2.5"
api_base = "https://api.together.ai/v1"
api_key_env = "TOGETHER_API_KEY"
temperature = 0.6
top_p = 0.95
reasoning_enabled = false


[[players]]
id = "BLUE"
type = "llm"
model = "gemini-2.0-flash"
#model = "MiniMaxAI/MiniMax-M2.5"
api_base = "https://generativelanguage.googleapis.com/v1beta/openai/"
#api_base = "https://api.together.ai/v1"
api_key_env = "GEMINI_API_KEY"
#api_key_env = "TOGETHER_API_KEY"
reasoning_enabled = false
timeout_seconds = 300
temperature = 0.6
top_p = 0.95


[[players]]
id = "WHITE"
type = "llm"
model = "gpt-4o-mini"
api_key_env = "OPENAI_API_KEY"
timeout_seconds = 300
temperature = 0.6
top_p = 0.95
